---

# Version 1.0.0

- hosts: "{{ HOSTS | default('all') }}"
  vars:
    backup_location: "/docker/backup/"
    container_list:
      - container_name: myShinyContainer1
      - container_name: myShinyContainer2

  tasks:
    - name: Backup Container
      include_tasks: do_backup.yml
      loop: "{{ container_list }}"